name: core-lightning

owner: ElementsProject
repo: lightning

language: C
ccs:
- dergoegge

engines:
- LibFuzzer
- AflPlusPlus
- HonggFuzz
- None
sanitizers:
- ValueProfile
- Undefined
- Address
- CmpLog
- Coverage
- None
