name: bitcoin

owner: bitcoin
repo: bitcoin

language: Cpp
ccs:
- dergoegge

engines:
- LibFuzzer
- AflPlusPlus
- None
sanitizers:
- Address
- Undefined
- Coverage
- CmpLog
- ValueProfile
- None

fuzz_env_var: FUZZ
